# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b56a0de63e1e326b31b57842f00fe6f15c9869f5590079ed4f6b88aa7e8699818ccac512a9e54bb830828a58d2d15998812aaf18e7f11d3b84cb7d81f27c7487

test:
  secret_key_base: c184d08be224a654b3d65a2d7b26b1d0c6aabb258158acd9f8c247cf488342e69d1f8401ee34253a10d42d750d2f0872667237c706636278cf9caf06ba8de044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
